name: video_trimmer
description: A Flutter package for trimming videos. This supports retrieving, trimming, and storage of trimmed video files to the file system.
version: 2.2.0
homepage: https://github.com/sbis04/video_trimmer

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  video_player: ^2.9.3
  ffmpeg_kit_flutter_full_gpl: ^6.0.3
  video_thumbnail: ^0.5.3
  path_provider: ^2.1.5
  intl: ^0.19.0
  path: ^1.9.1
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_lints: ^2.0.2
  lints: ^2.1.1

flutter:
